# Generated by Django 3.1.1 on 2020-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablemodel',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tablemodel',
            name='nickname',
        ),
    ]
